In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)

In [3]:
df_taiwan = pd.read_csv('data/data.csv')

In [4]:
df_taiwan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6819 entries, 0 to 6818
Data columns (total 96 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Bankrupt?                                                 6819 non-null   int64
 1    ROA(C) before interest and depreciation before interest  6819 non-null   float64
 2    ROA(A) before interest and % after tax                   6819 non-null   float64
 3    ROA(B) before interest and depreciation after tax        6819 non-null   float64
 4    Operating Gross Margin                                   6819 non-null   float64
 5    Realized Sales Gross Margin                              6819 non-null   float64
 6    Operating Profit Rate                                    6819 non-null   float64
 7    Pre-tax net Interest Rate                                6819 non-null   float64
 8    After-tax net Interest Rate                              6819 non-null   float64
 9    Non-industry income and expenditure/revenue              6819 non-null   float64
 10   Continuous interest rate (after tax)                     6819 non-null   float64
 11   Operating Expense Rate                                   6819 non-null   float64
 12   Research and development expense rate                    6819 non-null   float64
 13   Cash flow rate                                           6819 non-null   float64
 14   Interest-bearing debt interest rate                      6819 non-null   float64
 15   Tax rate (A)                                             6819 non-null   float64
 16   Net Value Per Share (B)                                  6819 non-null   float64
 17   Net Value Per Share (A)                                  6819 non-null   float64
 18   Net Value Per Share (C)                                  6819 non-null   float64
 19   Persistent EPS in the Last Four Seasons                  6819 non-null   float64
 20   Cash Flow Per Share                                      6819 non-null   float64
 21   Revenue Per Share (Yuan ¥)                               6819 non-null   float64
 22   Operating Profit Per Share (Yuan ¥)                      6819 non-null   float64
 23   Per Share Net profit before tax (Yuan ¥)                 6819 non-null   float64
 24   Realized Sales Gross Profit Growth Rate                  6819 non-null   float64
 25   Operating Profit Growth Rate                             6819 non-null   float64
 26   After-tax Net Profit Growth Rate                         6819 non-null   float64
 27   Regular Net Profit Growth Rate                           6819 non-null   float64
 28   Continuous Net Profit Growth Rate                        6819 non-null   float64
 29   Total Asset Growth Rate                                  6819 non-null   float64
 30   Net Value Growth Rate                                    6819 non-null   float64
 31   Total Asset Return Growth Rate Ratio                     6819 non-null   float64
 32   Cash Reinvestment %                                      6819 non-null   float64
 33   Current Ratio                                            6819 non-null   float64
 34   Quick Ratio                                              6819 non-null   float64
 35   Interest Expense Ratio                                   6819 non-null   float64
 36   Total debt/Total net worth                               6819 non-null   float64
 37   Debt ratio %                                             6819 non-null   float64
 38   Net worth/Assets                                         6819 non-null   float64
 39   Long-term fund suitability ratio (A)                     6819 non-null   float64
 40   Borrowing dependency                                     6819 non-null   float64
 41   Contingent liabilities/Net worth                         6819 non-null   float64
 42   Operating profit/Paid-in capital                         6819 non-null   float64
 43   Net profit before tax/Paid-in capital                    6819 non-null   float64
 44   Inventory and accounts receivable/Net value              6819 non-null   float64
 45   Total Asset Turnover                                     6819 non-null   float64
 46   Accounts Receivable Turnover                             6819 non-null   float64
 47   Average Collection Days                                  6819 non-null   float64
 48   Inventory Turnover Rate (times)                          6819 non-null   float64
 49   Fixed Assets Turnover Frequency                          6819 non-null   float64
 50   Net Worth Turnover Rate (times)                          6819 non-null   float64
 51   Revenue per person                                       6819 non-null   float64
 52   Operating profit per person                              6819 non-null   float64
 53   Allocation rate per person                               6819 non-null   float64
 54   Working Capital to Total Assets                          6819 non-null   float64
 55   Quick Assets/Total Assets                                6819 non-null   float64
 56   Current Assets/Total Assets                              6819 non-null   float64
 57   Cash/Total Assets                                        6819 non-null   float64
 58   Quick Assets/Current Liability                           6819 non-null   float64
 59   Cash/Current Liability                                   6819 non-null   float64
 60   Current Liability to Assets                              6819 non-null   float64
 61   Operating Funds to Liability                             6819 non-null   float64
 62   Inventory/Working Capital                                6819 non-null   float64
 63   Inventory/Current Liability                              6819 non-null   float64
 64   Current Liabilities/Liability                            6819 non-null   float64
 65   Working Capital/Equity                                   6819 non-null   float64
 66   Current Liabilities/Equity                               6819 non-null   float64
 67   Long-term Liability to Current Assets                    6819 non-null   float64
 68   Retained Earnings to Total Assets                        6819 non-null   float64
 69   Total income/Total expense                               6819 non-null   float64
 70   Total expense/Assets                                     6819 non-null   float64
 71   Current Asset Turnover Rate                              6819 non-null   float64
 72   Quick Asset Turnover Rate                                6819 non-null   float64
 73   Working capitcal Turnover Rate                           6819 non-null   float64
 74   Cash Turnover Rate                                       6819 non-null   float64
 75   Cash Flow to Sales                                       6819 non-null   float64
 76   Fixed Assets to Assets                                   6819 non-null   float64
 77   Current Liability to Liability                           6819 non-null   float64
 78   Current Liability to Equity                              6819 non-null   float64
 79   Equity to Long-term Liability                            6819 non-null   float64
 80   Cash Flow to Total Assets                                6819 non-null   float64
 81   Cash Flow to Liability                                   6819 non-null   float64
 82   CFO to Assets                                            6819 non-null   float64
 83   Cash Flow to Equity                                      6819 non-null   float64
 84   Current Liability to Current Assets                      6819 non-null   float64
 85   Liability-Assets Flag                                    6819 non-null   int64
 86   Net Income to Total Assets                               6819 non-null   float64
 87   Total assets to GNP price                                6819 non-null   float64
 88   No-credit Interval                                       6819 non-null   float64
 89   Gross Profit to Sales                                    6819 non-null   float64
 90   Net Income to Stockholder's Equity                       6819 non-null   float64
 91   Liability to Equity                                      6819 non-null   float64
 92   Degree of Financial Leverage (DFL)                       6819 non-null   float64
 93   Interest Coverage Ratio (Interest expense to EBIT)       6819 non-null   float64
 94   Net Income Flag                                          6819 non-null   int64
 95   Equity to Liability                                      6819 non-null   float64
dtypes: float64(93), int64(3)
memory usage: 5.0 MB

All columns names have a space before them, wrote a function to remove the space in their name

In [5]:
for column in df_taiwan.drop(columns = 'Bankrupt?').columns:
    print(column)

 ROA(C) before interest and depreciation before interest
 ROA(A) before interest and % after tax
 ROA(B) before interest and depreciation after tax
 Operating Gross Margin
 Realized Sales Gross Margin
 Operating Profit Rate
 Pre-tax net Interest Rate
 After-tax net Interest Rate
 Non-industry income and expenditure/revenue
 Continuous interest rate (after tax)
 Operating Expense Rate
 Research and development expense rate
 Cash flow rate
 Interest-bearing debt interest rate
 Tax rate (A)
 Net Value Per Share (B)
 Net Value Per Share (A)
 Net Value Per Share (C)
 Persistent EPS in the Last Four Seasons
 Cash Flow Per Share
 Revenue Per Share (Yuan ¥)
 Operating Profit Per Share (Yuan ¥)
 Per Share Net profit before tax (Yuan ¥)
 Realized Sales Gross Profit Growth Rate
 Operating Profit Growth Rate
 After-tax Net Profit Growth Rate
 Regular Net Profit Growth Rate
 Continuous Net Profit Growth Rate
 Total Asset Growth Rate
 Net Value Growth Rate
 Total Asset Return Growth Rate Ratio
 Cash Reinvestment %
 Current Ratio
 Quick Ratio
 Interest Expense Ratio
 Total debt/Total net worth
 Debt ratio %
 Net worth/Assets
 Long-term fund suitability ratio (A)
 Borrowing dependency
 Contingent liabilities/Net worth
 Operating profit/Paid-in capital
 Net profit before tax/Paid-in capital
 Inventory and accounts receivable/Net value
 Total Asset Turnover
 Accounts Receivable Turnover
 Average Collection Days
 Inventory Turnover Rate (times)
 Fixed Assets Turnover Frequency
 Net Worth Turnover Rate (times)
 Revenue per person
 Operating profit per person
 Allocation rate per person
 Working Capital to Total Assets
 Quick Assets/Total Assets
 Current Assets/Total Assets
 Cash/Total Assets
 Quick Assets/Current Liability
 Cash/Current Liability
 Current Liability to Assets
 Operating Funds to Liability
 Inventory/Working Capital
 Inventory/Current Liability
 Current Liabilities/Liability
 Working Capital/Equity
 Current Liabilities/Equity
 Long-term Liability to Current Assets
 Retained Earnings to Total Assets
 Total income/Total expense
 Total expense/Assets
 Current Asset Turnover Rate
 Quick Asset Turnover Rate
 Working capitcal Turnover Rate
 Cash Turnover Rate
 Cash Flow to Sales
 Fixed Assets to Assets
 Current Liability to Liability
 Current Liability to Equity
 Equity to Long-term Liability
 Cash Flow to Total Assets
 Cash Flow to Liability
 CFO to Assets
 Cash Flow to Equity
 Current Liability to Current Assets
 Liability-Assets Flag
 Net Income to Total Assets
 Total assets to GNP price
 No-credit Interval
 Gross Profit to Sales
 Net Income to Stockholder's Equity
 Liability to Equity
 Degree of Financial Leverage (DFL)
 Interest Coverage Ratio (Interest expense to EBIT)
 Net Income Flag
 Equity to Liability

In [6]:
for column in df_taiwan.drop(columns = 'Bankrupt?').columns:
    
    df_taiwan.rename(columns = {column: column[1:]}, inplace=True)

In [7]:
df_taiwan.columns

Index(['Bankrupt?', 'ROA(C) before interest and depreciation before interest',
       'ROA(A) before interest and % after tax',
       'ROA(B) before interest and depreciation after tax',
       'Operating Gross Margin', 'Realized Sales Gross Margin',
       'Operating Profit Rate', 'Pre-tax net Interest Rate',
       'After-tax net Interest Rate',
       'Non-industry income and expenditure/revenue',
       'Continuous interest rate (after tax)', 'Operating Expense Rate',
       'Research and development expense rate', 'Cash flow rate',
       'Interest-bearing debt interest rate', 'Tax rate (A)',
       'Net Value Per Share (B)', 'Net Value Per Share (A)',
       'Net Value Per Share (C)', 'Persistent EPS in the Last Four Seasons',
       'Cash Flow Per Share', 'Revenue Per Share (Yuan ¥)',
       'Operating Profit Per Share (Yuan ¥)',
       'Per Share Net profit before tax (Yuan ¥)',
       'Realized Sales Gross Profit Growth Rate',
       'Operating Profit Growth Rate', 'After-tax Net Profit Growth Rate',
       'Regular Net Profit Growth Rate', 'Continuous Net Profit Growth Rate',
       'Total Asset Growth Rate', 'Net Value Growth Rate',
       'Total Asset Return Growth Rate Ratio', 'Cash Reinvestment %',
       'Current Ratio', 'Quick Ratio', 'Interest Expense Ratio',
       'Total debt/Total net worth', 'Debt ratio %', 'Net worth/Assets',
       'Long-term fund suitability ratio (A)', 'Borrowing dependency',
       'Contingent liabilities/Net worth', 'Operating profit/Paid-in capital',
       'Net profit before tax/Paid-in capital',
       'Inventory and accounts receivable/Net value', 'Total Asset Turnover',
       'Accounts Receivable Turnover', 'Average Collection Days',
       'Inventory Turnover Rate (times)', 'Fixed Assets Turnover Frequency',
       'Net Worth Turnover Rate (times)', 'Revenue per person',
       'Operating profit per person', 'Allocation rate per person',
       'Working Capital to Total Assets', 'Quick Assets/Total Assets',
       'Current Assets/Total Assets', 'Cash/Total Assets',
       'Quick Assets/Current Liability', 'Cash/Current Liability',
       'Current Liability to Assets', 'Operating Funds to Liability',
       'Inventory/Working Capital', 'Inventory/Current Liability',
       'Current Liabilities/Liability', 'Working Capital/Equity',
       'Current Liabilities/Equity', 'Long-term Liability to Current Assets',
       'Retained Earnings to Total Assets', 'Total income/Total expense',
       'Total expense/Assets', 'Current Asset Turnover Rate',
       'Quick Asset Turnover Rate', 'Working capitcal Turnover Rate',
       'Cash Turnover Rate', 'Cash Flow to Sales', 'Fixed Assets to Assets',
       'Current Liability to Liability', 'Current Liability to Equity',
       'Equity to Long-term Liability', 'Cash Flow to Total Assets',
       'Cash Flow to Liability', 'CFO to Assets', 'Cash Flow to Equity',
       'Current Liability to Current Assets', 'Liability-Assets Flag',
       'Net Income to Total Assets', 'Total assets to GNP price',
       'No-credit Interval', 'Gross Profit to Sales',
       'Net Income to Stockholder's Equity', 'Liability to Equity',
       'Degree of Financial Leverage (DFL)',
       'Interest Coverage Ratio (Interest expense to EBIT)', 'Net Income Flag',
       'Equity to Liability'],
      dtype='object')

In [8]:
# drop these columns because they are a constant
df_taiwan.drop(columns= ['Liability-Assets Flag', 'Net Income Flag'], inplace=True)

In [9]:
df_taiwan

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Current Liability to Current Assets,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Equity to Liability
0,1,0.370594,0.424389,0.405750,0.601457,0.601457,0.998969,0.796887,0.808809,0.302646,...,0.118250,0.716845,0.009219,0.622879,0.601453,0.827890,0.290202,0.026601,0.564050,0.016469
1,1,0.464291,0.538214,0.516730,0.610235,0.610235,0.998946,0.797380,0.809301,0.303556,...,0.047775,0.795297,0.008323,0.623652,0.610237,0.839969,0.283846,0.264577,0.570175,0.020794
2,1,0.426071,0.499019,0.472295,0.601450,0.601364,0.998857,0.796403,0.808388,0.302035,...,0.025346,0.774670,0.040003,0.623841,0.601449,0.836774,0.290189,0.026555,0.563706,0.016474
3,1,0.399844,0.451265,0.457733,0.583541,0.583541,0.998700,0.796967,0.808966,0.303350,...,0.067250,0.739555,0.003252,0.622929,0.583538,0.834697,0.281721,0.026697,0.564663,0.023982
4,1,0.465022,0.538432,0.522298,0.598783,0.598783,0.998973,0.797366,0.809304,0.303475,...,0.047725,0.795016,0.003878,0.623521,0.598782,0.839973,0.278514,0.024752,0.575617,0.035490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6814,0,0.493687,0.539468,0.543230,0.604455,0.604462,0.998992,0.797409,0.809331,0.303510,...,0.027951,0.799927,0.000466,0.623620,0.604455,0.840359,0.279606,0.027064,0.566193,0.029890
6815,0,0.475162,0.538269,0.524172,0.598308,0.598308,0.998992,0.797414,0.809327,0.303520,...,0.031470,0.799748,0.001959,0.623931,0.598306,0.840306,0.278132,0.027009,0.566018,0.038284
6816,0,0.472725,0.533744,0.520638,0.610444,0.610213,0.998984,0.797401,0.809317,0.303512,...,0.007542,0.797778,0.002840,0.624156,0.610441,0.840138,0.275789,0.026791,0.565158,0.097649
6817,0,0.506264,0.559911,0.554045,0.607850,0.607850,0.999074,0.797500,0.809399,0.303498,...,0.022916,0.811808,0.002837,0.623957,0.607846,0.841084,0.277547,0.026822,0.565302,0.044009
6818,0,0.493053,0.570105,0.549548,0.627409,0.627409,0.998080,0.801987,0.813800,0.313415,...,0.005579,0.815956,0.000707,0.626680,0.627408,0.841019,0.275114,0.026793,0.565167,0.233902

In [10]:
for column in df_taiwan.drop(columns= ['Bankrupt?', 'Tax rate (A)']).columns:
    zeros = [df_taiwan[column] == 0]

In [11]:
zeros

[0       False
 1       False
 2       False
 3       False
 4       False
         ...
 6814    False
 6815    False
 6816    False
 6817    False
 6818    False
 Name: Equity to Liability, Length: 6819, dtype: bool]

In [12]:
df_1 = pd.read_csv('data/1year.csv')

df_2 = pd.read_csv('data/2year.csv')

df_3 = pd.read_csv('data/3year.csv')

df_4 = pd.read_csv('data/4year.csv')

df_5 = pd.read_csv('data/5year.csv')

C:\Users\tonyt\anaconda3\envs\dsi\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (0,1,2,5,6,8,9,10,13,17,21,23,24,28,34,35,37,47,50,54,56,58) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\tonyt\anaconda3\envs\dsi\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (14,23) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\tonyt\anaconda3\envs\dsi\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (0,1,2,5,6,7,9,10,13,14,15,16,17,21,23,24,25,28,33,34,35,37,47,49,50,56,58) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [13]:
df_1

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,...,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64,class
0,0.20055,0.37951,0.39641,2.0472,32.351,0.38825,0.24976,1.3305,1.1389,0.50494,...,0.121960,0.39718,0.87804,0.001924,8.416,5.1372,82.658,4.4158,7.4277,0
1,0.20912,0.49988,0.47225,1.9447,14.786,0,0.25834,0.99601,1.6996,0.49788,...,0.121300,0.42002,0.85300,0,4.1486,3.2732,107.350,3.4,60.987,0
2,0.24866,0.69592,0.26713,1.5548,-1.1523,0,0.30906,0.43695,1.309,0.30408,...,0.241140,0.81774,0.76599,0.69484,4.9909,3.951,134.270,2.7185,5.2078,0
3,0.081483,0.30734,0.45879,2.4928,51.952,0.14988,0.092704,1.8661,1.0571,0.57353,...,0.054015,0.14207,0.94598,0,4.5746,3.6147,86.435,4.2228,5.5497,0
4,0.18732,0.61323,0.2296,1.4063,-7.3128,0.18732,0.18732,0.6307,1.1559,0.38677,...,0.134850,0.48431,0.86515,0.12444,6.3985,4.3158,127.210,2.8692,7.898,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7007,0.038665,0.071884,0.48884,7.8004,221.01,0.038665,0.045892,11.068,1.0765,0.7956,...,0.071070,0.048599,0.92893,0,2.147,1.4679,53.735,6.7926,1.1116,1
7008,0.001091,0.8516,0.003463,1.0086,-44.467,0.086248,0.001091,0.17429,1.0297,0.14842,...,-0.198900,0.007349,0.97403,2.0331,6.8515,4.1096,142.830,2.5556,1.7346,1
7009,-0.091442,0.7055,-0.047216,0.92568,-7.2952,0,-0.090374,0.41744,9.1345,0.2945,...,0.000966,-0.31049,1.00740,0.077583,72.893,20.79,25.384,14.379,22.18,1
7010,0.13809,3.3357,-2.364,0.29128,-88.382,-3.3963,0.13809,-0.70021,9.9852,-2.3357,...,0.011347,-0.059122,0.97866,0,231.9,12.651,121.930,2.9935,351.85,1
7011,0.098271,0.8333,0.000426,1.0005,-43.191,0,0.12838,0.20019,2.5144,0.16682,...,0.150320,0.58909,0.85877,0,9.2728,4.9207,116.480,3.1336,12.748,1

In [14]:
df_2

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,...,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64,class
0,0.20235,0.465,0.24038,1.5171,-14.547,0.51069,0.25366,0.91816,1.1519,0.42695,...,0.13184,0.47395,0.86816,0.00024,8.5487,5.1655,107.74,3.3879,5.344,0
1,0.030073,0.59563,0.18668,1.3382,-37.859,-0.000319,0.04167,0.6789,0.32356,0.40437,...,0.12146,0.074369,0.87235,0,1.5264,0.63305,622.66,0.58619,1.2381,0
2,0.25786,0.29949,0.66519,3.2211,71.799,0,0.31877,2.332,1.6762,0.69841,...,0.16499,0.36921,0.81614,0,4.3325,3.1985,65.215,5.5969,47.466,0
3,0.22716,0.6785,0.042784,1.0828,-88.212,0,0.28505,0.47384,1.3241,0.3215,...,0.29358,0.70657,0.78617,0.48456,5.2309,5.0675,142.46,2.5621,3.0066,0
4,0.085443,0.38039,0.35923,1.9444,21.731,0.1879,0.10823,1.3714,1.1126,0.52167,...,0.10124,0.16379,0.89876,0,5.7035,4.002,89.058,4.0984,5.9874,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10168,0.02997,0.66806,0.066243,1.1103,-105.55,0.02997,0.038888,0.48274,1.0292,0.3225,...,0.028377,0.092931,0.97162,0.20982,3.0914,3.9456,192.22,1.8988,3.4199,1
10169,0.012843,0.49306,-0.16062,0.61898,-24.801,0.012843,0.012843,0.9059,1.0145,0.44666,...,0.014247,0.028752,0.98575,0.16009,48.666,63.752,40.071,9.1087,5.1956,1
10170,0.015092,0.55759,-0.2846,0.48599,-85.571,0.015092,0.009826,0.69488,1.006,0.38746,...,0.005971,0.03895,0.99403,0.010091,15.053,11.964,114.25,3.1948,2.4201,1
10171,-0.002554,0.47076,0.42401,1.9007,0.95483,-0.002554,0.001785,1.1144,0.99293,0.52464,...,-0.007122,-0.004869,1.0071,0,6.4289,5.7025,64.291,5.6773,25.399,1
10172,0.002072,0.94315,-0.13474,0.85607,-119.92,0.015226,0.002072,0.059818,1.7749,0.056417,...,0.031154,0.03672,0.9622,0.1328,4.1618,4.9734,192.51,1.896,8.9562,1

In [15]:
df_poland = pd.concat([df_1,df_2,df_3,df_4,df_5])

In [16]:
df_poland

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,...,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64,class
0,0.20055,0.37951,0.39641,2.0472,32.351,0.38825,0.24976,1.3305,1.1389,0.50494,...,0.12196,0.39718,0.87804,0.001924,8.416,5.1372,82.658,4.4158,7.4277,0
1,0.20912,0.49988,0.47225,1.9447,14.786,0,0.25834,0.99601,1.6996,0.49788,...,0.1213,0.42002,0.853,0,4.1486,3.2732,107.35,3.4,60.987,0
2,0.24866,0.69592,0.26713,1.5548,-1.1523,0,0.30906,0.43695,1.309,0.30408,...,0.24114,0.81774,0.76599,0.69484,4.9909,3.951,134.27,2.7185,5.2078,0
3,0.081483,0.30734,0.45879,2.4928,51.952,0.14988,0.092704,1.8661,1.0571,0.57353,...,0.054015,0.14207,0.94598,0,4.5746,3.6147,86.435,4.2228,5.5497,0
4,0.18732,0.61323,0.2296,1.4063,-7.3128,0.18732,0.18732,0.6307,1.1559,0.38677,...,0.13485,0.48431,0.86515,0.12444,6.3985,4.3158,127.21,2.8692,7.898,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5422,0.012898,0.70621,0.038857,1.1722,-18.907,0,0.013981,0.416,1.6768,0.29379,...,0.020169,0.043904,1.0122,1.2594,13.472,12.432,49.117,7.4313,2.2799,1
5423,-0.57805,0.96702,-0.80085,0.16576,-67.365,-0.57805,-0.57805,-0.40334,0.93979,-0.39004,...,-0.064073,1.482,1.0641,-0.018084,110.72,44.759,81.22,4.494,5.1305,1
5424,-0.17905,1.2553,-0.27599,0.74554,-120.44,-0.17905,-0.15493,-0.26018,1.1749,-0.32659,...,0.14888,0.54824,0.85112,-0.52243,9.8526,3.4892,207.87,1.7559,9.9527,1
5425,-0.10886,0.74394,0.015449,1.0878,-17.003,-0.10886,-0.10918,0.12531,0.84516,0.093224,...,-0.1832,-1.1677,1.1832,6.0924,13.886,6.0769,83.122,4.3911,0.95575,1
5426,-0.10537,0.53629,-0.045578,0.91478,-56.068,-0.10537,-0.10994,0.8646,0.9504,0.46367,...,-0.052186,-0.22725,1.0522,0.003196,7.7332,4.7174,136.85,2.6672,2.7927,1

In [17]:
df_poland.columns

Index(['Attr1', 'Attr2', 'Attr3', 'Attr4', 'Attr5', 'Attr6', 'Attr7', 'Attr8',
       'Attr9', 'Attr10', 'Attr11', 'Attr12', 'Attr13', 'Attr14', 'Attr15',
       'Attr16', 'Attr17', 'Attr18', 'Attr19', 'Attr20', 'Attr21', 'Attr22',
       'Attr23', 'Attr24', 'Attr25', 'Attr26', 'Attr27', 'Attr28', 'Attr29',
       'Attr30', 'Attr31', 'Attr32', 'Attr33', 'Attr34', 'Attr35', 'Attr36',
       'Attr37', 'Attr38', 'Attr39', 'Attr40', 'Attr41', 'Attr42', 'Attr43',
       'Attr44', 'Attr45', 'Attr46', 'Attr47', 'Attr48', 'Attr49', 'Attr50',
       'Attr51', 'Attr52', 'Attr53', 'Attr54', 'Attr55', 'Attr56', 'Attr57',
       'Attr58', 'Attr59', 'Attr60', 'Attr61', 'Attr62', 'Attr63', 'Attr64',
       'class'],
      dtype='object')

In [18]:
poland_cols = {
    'Attr1': 'net profit/ total assets',
    'Attr2': 'total liabilities / total assets',
    'Attr3': 'working capital / total assets',
    'Attr4': 'current assets / short-term liabilities',
    'Attr5': 'cash + short-term securities + receivables - short-term liabilities) / (operating expenses - depreciation)*365',
    'Attr6': 'retained earnings / total assets',
    'Attr7': 'EBIT / total assets',
    'Attr8': 'book value of equity / total liabilities',
    'Attr9': 'sales / total assets',
    'Attr10': 'equity / total assets',
    'Attr11': '(gross profit + extraordinary items + financial expenses) / total assets',
    'Attr12': 'gross profit / short-term liabilities',
    'Attr13': '(gross profit + depreciation) / sales',
    'Attr14': '(gross profit + interest) / total assets',
    'Attr15': '(total liabilities * 365) / (gross profit + depreciation)',
    'Attr16': '(gross profit + depreciation) / total liabilities',
    'Attr17': 'total assets / total liabilities',
    'Attr18': 'gross profit / total assets',
    'Attr19': 'gross profit / sales',
    'Attr20': '(inventory * 365) / sales',
    'Attr21': 'sales (n) / sales (n-1)',
    'Attr22': 'profit on operating activities / total assets',
    'Attr23': 'net profit / sales',
    'Attr24': 'gross profit (in 3 years) / total assets',
    'Attr25': '(equity - share capital) / total assets',
    'Attr26': '(net profit + depreciation) / total liabilities',
    'Attr27': 'profit on operating activities / financial expenses',
    'Attr28': 'working capital / fixed assets',
    'Attr29': 'logarithm of total assets',
    'Attr30': '(total liabilities - cash) / sales',
    'Attr31': '(gross profit + interest) / sales',
    'Attr32': '(current liabilities * 365) / cost of products sold',
    'Attr33': 'operating expenses / short-term liabilities',
    'Attr34': 'operating expenses / total liabilities',
    'Attr35': 'profit on sales / total assets',
    'Attr36': 'total sales / total assets',
    'Attr37': '(current assets - inventories) / long-term liabilities',
    'Attr38': 'constant capital / total assets',
    'Attr39': 'profit on sales / sales',
    'Attr40': '(current assets - inventory - receivables) / short-term liabilities',
    'Attr41': 'total liabilities / ((profit on operating activities + depreciation) * (12/365))',
    'Attr42': 'profit on operating activities / sales',
    'Attr43': 'rotation receivables + inventory turnover in days',
    'Attr44': '(receivables * 365) / sales',
    'Attr45': 'net profit / inventory',
    'Attr46': '(current assets - inventory) / short-term liabilities',
    'Attr47': '(inventory * 365) / cost of products sold',
    'Attr48': 'EBITDA (profit on operating activities - depreciation) / total assets',
    'Attr49': 'EBITDA (profit on operating activities - depreciation) / sales',
    'Attr50': 'current assets / total liabilities',
    'Attr51': 'short-term liabilities / total assets',
    'Attr52': '(short-term liabilities * 365) / cost of products sold)',
    'Attr53': 'equity / fixed assets',
    'Attr54': 'constant capital / fixed assets',
    'Attr55': 'working capital',
    'Attr56': '(sales - cost of products sold) / sales',
    'Attr57': '(current assets - inventory - short-term liabilities) / (sales - gross profit - depreciation)',
    'Attr58': 'total costs /total sales',
    'Attr59': 'long-term liabilities / equity',
    'Attr60': 'sales / inventory',
    'Attr61': 'sales / receivables',
    'Attr62': '(short-term liabilities *365) / sales',
    'Attr63': 'sales / short-term liabilities',
    'Attr64': 'sales / fixed assets',
    'class': 'Bankrupt'
}

In [19]:
df_poland.rename(columns= poland_cols, inplace=True)

In [20]:
df_poland

,net profit/ total assets,total liabilities / total assets,working capital / total assets,current assets / short-term liabilities,cash + short-term securities + receivables - short-term liabilities) / (operating expenses - depreciation)*365,retained earnings / total assets,EBIT / total assets,book value of equity / total liabilities,sales / total assets,equity / total assets,...,(sales - cost of products sold) / sales,(current assets - inventory - short-term liabilities) / (sales - gross profit - depreciation),total costs /total sales,long-term liabilities / equity,sales / inventory,sales / receivables,(short-term liabilities *365) / sales,sales / short-term liabilities,sales / fixed assets,Bankrupt
0,0.20055,0.37951,0.39641,2.0472,32.351,0.38825,0.24976,1.3305,1.1389,0.50494,...,0.12196,0.39718,0.87804,0.001924,8.416,5.1372,82.658,4.4158,7.4277,0
1,0.20912,0.49988,0.47225,1.9447,14.786,0,0.25834,0.99601,1.6996,0.49788,...,0.1213,0.42002,0.853,0,4.1486,3.2732,107.35,3.4,60.987,0
2,0.24866,0.69592,0.26713,1.5548,-1.1523,0,0.30906,0.43695,1.309,0.30408,...,0.24114,0.81774,0.76599,0.69484,4.9909,3.951,134.27,2.7185,5.2078,0
3,0.081483,0.30734,0.45879,2.4928,51.952,0.14988,0.092704,1.8661,1.0571,0.57353,...,0.054015,0.14207,0.94598,0,4.5746,3.6147,86.435,4.2228,5.5497,0
4,0.18732,0.61323,0.2296,1.4063,-7.3128,0.18732,0.18732,0.6307,1.1559,0.38677,...,0.13485,0.48431,0.86515,0.12444,6.3985,4.3158,127.21,2.8692,7.898,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5422,0.012898,0.70621,0.038857,1.1722,-18.907,0,0.013981,0.416,1.6768,0.29379,...,0.020169,0.043904,1.0122,1.2594,13.472,12.432,49.117,7.4313,2.2799,1
5423,-0.57805,0.96702,-0.80085,0.16576,-67.365,-0.57805,-0.57805,-0.40334,0.93979,-0.39004,...,-0.064073,1.482,1.0641,-0.018084,110.72,44.759,81.22,4.494,5.1305,1
5424,-0.17905,1.2553,-0.27599,0.74554,-120.44,-0.17905,-0.15493,-0.26018,1.1749,-0.32659,...,0.14888,0.54824,0.85112,-0.52243,9.8526,3.4892,207.87,1.7559,9.9527,1
5425,-0.10886,0.74394,0.015449,1.0878,-17.003,-0.10886,-0.10918,0.12531,0.84516,0.093224,...,-0.1832,-1.1677,1.1832,6.0924,13.886,6.0769,83.122,4.3911,0.95575,1
5426,-0.10537,0.53629,-0.045578,0.91478,-56.068,-0.10537,-0.10994,0.8646,0.9504,0.46367,...,-0.052186,-0.22725,1.0522,0.003196,7.7332,4.7174,136.85,2.6672,2.7927,1

In [21]:
df_taiwan.corr()[['Bankrupt?']].sort_values(by = 'Bankrupt?')

                                                    Bankrupt?
Net Income to Total Assets                          -0.315457
ROA(A) before interest and % after tax              -0.282941
ROA(B) before interest and depreciation after tax   -0.273051
ROA(C) before interest and depreciation before ...  -0.260807
Net worth/Assets                                    -0.250161
...                                                       ...
Current Liability to Current Assets                  0.171306
Borrowing dependency                                 0.176543
Current Liability to Assets                          0.194494
Debt ratio %                                         0.250161
Bankrupt?                                            1.000000

[94 rows x 1 columns]

In [22]:
for column in df_poland.columns:
    print(df_poland[column].unique())

['0.20055' '0.20912' '0.24866' ... '-0.17905' '-0.10886' '-0.10537']
['0.37951' '0.49988' '0.69592' ... '0.96702' '1.2553' '0.53629']
['0.39641' '0.47225' '0.26713' ... '-0.27599' '0.015449' '-0.045578']
['2.0472' '1.9447' '1.5548' ... '0.16576' '0.74554' '0.91478']
['32.351' '14.786' '-1.1523' ... '-120.44' '-17.003' '-56.068']
['0.38825' '0' '0.14988' ... '-0.17905' '-0.10886' '-0.10537']
['0.24976' '0.25834' '0.30906' ... '-0.15493' '-0.10918' '-0.10994']
['1.3305' '0.99601' '0.43695' ... '-0.26018' '0.12531' '0.8646']
['1.1389' '1.6996' '1.309' ... '0.93979' '0.84516' '0.9504']
['0.50494' '0.49788' '0.30408' ... '-0.39004' '-0.32659' '0.093224']
['0.24976' '0.26114' '0.31258' ... '-0.15493' '-0.10918' '-0.10994']
['0.6598' '0.5168' '0.64184' ... '-0.14284' '-0.62038' '-0.20557']
[0.1666 0.15835 0.24435 ... -0.07293999999999999 -0.065652 -0.066747]
['0.24976' '0.25834' '0.30906' ... '-0.15493' '-0.10918' '-0.10994']
['497.42' '677.96' '794.16' ... '-742.28' '-3298.2' '-5352.1']
['0.73378' '0.53838' '0.45961' ... '-0.49173' '-0.068197' '-0.17754']
['2.6349' '2.0005' '1.4369' ... '0.76973' '4.4473' '0.79665']
['0.24976' '0.25834' '0.30906' ... '-0.15493' '-0.10918' '-0.10994']
[0.14942 0.152 0.2361 ... -0.08135 -0.14128 -0.077072]
[43.37 87.98100000000001 73.133 ... 37.046 26.285 47.199]
['1.2479' '1.4293' '1.4283' ... '0.57674' '0.6477' '0.71351']
['0.21402' '0.24806' '0.3026' ... '-0.53492' '-0.09995' '-0.082947']
[0.11997999999999999 0.12304000000000001 0.18996 ... -0.094015
 -0.14085999999999999 -0.07386799999999999]
['0.47706' '?' '0.17193' ... '-0.57805' '-0.15493' '-0.10918']
['0.50494' '0.39542' '0.28932' ... '-0.39004' '-0.32659' '0.093224']
['0.60411' '0.43992' '0.37282' ... '-0.12988' '-0.067762' '-0.16902']
['1.4582' '88.444' '86.011' ... '100.33' '3.4212' '-6.1342']
['1.7615' '16.946' '1.0627' ... '-1.4423' '0.019106' '-0.089234']
['5.9443' '3.6884' '4.3749' ... '3.1535' '4.0622' '4.8555']
[0.11788 0.26969 0.41928999999999994 ... 0.65813 0.95181 0.37528]
[0.14942 0.152 0.23815 ... -0.08135 -0.14128 -0.077072]
['94.14' '122.17' '176.93' ... '76.33' '244.23' '70.252']
['3.8772' '2.9876' '2.063' ... '1.4945' '5.1956' '2.8064']
['0.56393' '2.9876' '1.4274' ... '-0.55316' '0.14077' '-0.15467']
['0.21402' '0.20616' '0.31565' ... '0.1767' '-0.09995' '-0.082947']
['1.741' '1.6996' '1.309' ... '1.9515' '0.83553' '1.4481']
['593.27' '?' '2.3019' ... '3.6065' '0.23908' '205.69']
['0.50591' '0.49788' '0.51537' ... '-0.38299' '-0.15597' '0.46515']
[0.12804000000000001 0.1213 0.24114000000000002 ... 0.09278 -0.12934
 -0.058149]
['0.66295' '0.086422' '0.32202' ... '0.064095' '0.048976' '0.004456']
['0.051402' '0.064371' '0.07402' ... '0.21414' '-0.5893' '-0.25846']
[0.12804000000000001 0.14595 0.23117 ... 0.09278 -0.12934 -0.058149]
[114.42 199.49 165.51 ... 56.452 11.450999999999999 86.348]
[71.05 111.51 92.381 ... 8.1548 104.61 60.06399999999999]
['1.0097' '0.51045' '0.94807' ... '-0.9263' '-1.9561' '-0.57124']
['1.5225' '1.1252' '1.0101' ... '0.56733' '0.77157' '0.56987']
['49.394' '100.13' '96.372' ... '43.526' '22.215' '44.858']
['0.1853' '0.23727' '0.29181' ... '-0.26922' '-0.63746' '-0.097675']
[0.11085 0.13960999999999998 0.22293000000000002 ... 0.08437
 -0.20496999999999999 -0.06847400000000001]
['2.042' '1.9447' '1.0758' ... '0.16455' '0.64421' '0.25733']
['0.37854' '0.49988' '0.48152' ... '0.95997' '1.0846' '0.53481']
['0.25792' '0.33472' '0.48474' ... '0.20741' '0.20912' '0.66913']
['2.2437' '17.866' '1.2098' ... '-1.7067' '0.1153' '0.90779']
['2.248' '17.866' '2.0504' ... '0.74181' '-0.45546' '-0.81508']
[348690.0 2304.6 6332.7 ... -9242.1 -58253.0 -425.13]
[0.12195999999999999 0.1213 0.24114000000000002 ... 0.14887999999999998
 -0.1832 -0.052186]
['0.39718' '0.42002' '0.81774' ... '0.54824' '-1.1677' '-0.22725']
[0.8780399999999999 0.853 0.76599 ... 1.0641 0.8511200000000001 1.1832]
['0.001924' '0' '0.69484' ... '-0.52243' '6.0924' '0.003196']
['8.416' '4.1486' '4.9909' ... '110.72' '9.8526' '7.7332']
['5.1372' '3.2732' '3.951' ... '3.4892' '6.0769' '4.7174']
[82.65799999999999 107.35 134.27 ... 49.117 207.87 83.12200000000001]
['4.4158' '3.4' '2.7185' ... '3.9105' '1.7559' '4.3911']
['7.4277' '60.987' '5.2078' ... '5.1305' '9.9527' '0.95575']
[0 1]

In [23]:
for column in df_poland.columns:
    df_poland[column].replace('?', np.nan, inplace=True)
    df_poland[column] = df_poland[column].astype('float')

In [24]:
df_poland.isnull().sum()

net profit/ total assets                                                                                            8
total liabilities / total assets                                                                                    8
working capital / total assets                                                                                      8
current assets / short-term liabilities                                                                           133
cash + short-term securities + receivables - short-term liabilities) / (operating expenses - depreciation)*365     87
                                                                                                                 ...
sales / receivables                                                                                               100
(short-term liabilities *365) / sales                                                                             126
sales / short-term liabilities                                                                                    133
sales / fixed assets                                                                                              798
Bankrupt                                                                                                            0
Length: 65, dtype: int64

In [25]:
df_poland.dropna(inplace=True)

In [26]:
df_poland.isnull().sum()

net profit/ total assets                                                                                          0
total liabilities / total assets                                                                                  0
working capital / total assets                                                                                    0
current assets / short-term liabilities                                                                           0
cash + short-term securities + receivables - short-term liabilities) / (operating expenses - depreciation)*365    0
                                                                                                                 ..
sales / receivables                                                                                               0
(short-term liabilities *365) / sales                                                                             0
sales / short-term liabilities                                                                                    0
sales / fixed assets                                                                                              0
Bankrupt                                                                                                          0
Length: 65, dtype: int64

In [27]:
poland = df_poland.to_csv('data/poland.csv', index = None)

taiwan = df_taiwan.to_csv('data/taiwan.csv', index = None)